/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.areaCirculo;

import java.awt.event.KeyEvent;

/**
 *
 * @author IPT
 */
public class AreaGui extends javax.swing.JFrame {

    /**
     * Creates new form Equation2gGui
     */
    public AreaGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        sldRadius = new javax.swing.JSlider();
        txtRadius = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btCalculate = new javax.swing.JButton();
        txtArea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circleArea.png"))); // NOI18N
        jLabel1.setText("Cálculo da área do Círculo");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Raio"));
        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        sldRadius.setValue(0);
        sldRadius.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldRadiusStateChanged(evt);
            }
        });
        jPanel3.add(sldRadius);

        txtRadius.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRadius.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRadius.setText("0");
        txtRadius.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRadiusKeyPressed(evt);
            }
        });
        jPanel3.add(txtRadius);

        jPanel2.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Área"));
        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        btCalculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/calculate.png"))); // NOI18N
        btCalculate.setText("Calcular");
        btCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculateActionPerformed(evt);
            }
        });
        jPanel4.add(btCalculate);

        txtArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtArea.setText("0");
        jPanel4.add(txtArea);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculateActionPerformed
        double radius= Double.valueOf(txtRadius.getText());
        double area = Math.PI * Math.pow(radius, 2);
        txtArea.setText(area + "");
    }//GEN-LAST:event_btCalculateActionPerformed

    private void sldRadiusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldRadiusStateChanged
        txtRadius.setText( sldRadius.getValue()/ 10.0  + "");
        btCalculateActionPerformed(null);
    }//GEN-LAST:event_sldRadiusStateChanged

    private void txtRadiusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRadiusKeyPressed
       if( evt.getKeyCode() == KeyEvent.VK_ENTER){
           btCalculateActionPerformed(null);
       }
    }//GEN-LAST:event_txtRadiusKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider sldRadius;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtRadius;
    // End of variables declaration//GEN-END:variables
}
