package MyArkanoid;

/**
 *
 * @author Pedro Coelho - 25026
 * @author Jose Martins - 24269
 * 
 */
public class MenuPausa extends javax.swing.JFrame {
private ArkanoidGame jogo;
    static void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form MenuPausa
     */
    public MenuPausa(ArkanoidGame jogo) {
    initComponents();
    setLocationRelativeTo(null);
    this.jogo = jogo; // Guardamos a instância atual do jogo
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        esc_conti = new javax.swing.JButton();
        esc_sair = new javax.swing.JButton();
        esc_niveis = new javax.swing.JButton();
        esc_restart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        esc_conti.setText("Continuar");
        esc_conti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esc_contiActionPerformed(evt);
            }
        });

        esc_sair.setText("Sair");
        esc_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esc_sairActionPerformed(evt);
            }
        });

        esc_niveis.setText("Niveis");
        esc_niveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esc_niveisActionPerformed(evt);
            }
        });

        esc_restart.setText("ReStart");
        esc_restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esc_restartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(esc_restart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(esc_conti, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(esc_niveis, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esc_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(esc_conti, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(esc_restart, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(esc_niveis, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(esc_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        esc_sair.getAccessibleContext().setAccessibleName("esc_sair");
        esc_niveis.getAccessibleContext().setAccessibleName("esc_niveis");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void esc_niveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esc_niveisActionPerformed
        setVisible(false);
        new Niveis().setVisible(true);
        //this.jogo.dispose();
        this.dispose();// TODO add your handling code here:
        
    }//GEN-LAST:event_esc_niveisActionPerformed

    private void esc_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esc_sairActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_esc_sairActionPerformed

    private void esc_contiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esc_contiActionPerformed
         if (jogo != null) {
        jogo.continuarJogo(); // Recomeça o jogo
    }
    this.dispose(); // Fecha a janela do menu
        // TODO add your handling code here:
    }//GEN-LAST:event_esc_contiActionPerformed

    private void esc_restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esc_restartActionPerformed
        //new ArkanoidGame().restart();// TODO add your handling code here:
    }//GEN-LAST:event_esc_restartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton esc_conti;
    private javax.swing.JButton esc_niveis;
    private javax.swing.JButton esc_restart;
    private javax.swing.JButton esc_sair;
    // End of variables declaration//GEN-END:variables
}
