package MyArkanoid;

/**
 *
 * @author jooma
 */
public class Niveis extends javax.swing.JFrame {

    /**
     * Creates new form Niveis
     */
    public Niveis() {
        initComponents();
        jLabel2.setOpaque(true);
        jLabel2.setBackground(new java.awt.Color(211, 211, 211, 200)); // light gray com transparência alpha=100
        setLocationRelativeTo(null);//coloca ao centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nivel_2 = new javax.swing.JButton();
        nivel_1 = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(500, 426));
        getContentPane().setLayout(null);

        nivel_2.setText("Nivel 1");
        nivel_2.setBorder(null);
        nivel_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivel_2ActionPerformed(evt);
            }
        });
        getContentPane().add(nivel_2);
        nivel_2.setBounds(50, 70, 62, 16);

        nivel_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nivel1nosniveis.png"))); // NOI18N
        nivel_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nivel_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivel_1ActionPerformed(evt);
            }
        });
        getContentPane().add(nivel_1);
        nivel_1.setBounds(30, 20, 100, 102);

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(190, 350, 72, 23);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 450, 370);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/smashtheagesnosniveis.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivel_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivel_1ActionPerformed
            setVisible(false);
            new playGame(this).setVisible(true);                // TODO add your handling code here:
    }//GEN-LAST:event_nivel_1ActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        setVisible(false);
        new arkanoide_exe.Arkanoide().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_voltarActionPerformed

    private void nivel_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivel_2ActionPerformed
       setVisible(false);
            new playGame(this).setVisible(true);
    }//GEN-LAST:event_nivel_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Niveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Niveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Niveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Niveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Niveis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nivel_1;
    private javax.swing.JButton nivel_2;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
