package MyArkanoid;

/**
 *
 * @author pedro
 */
public class playGame2 extends javax.swing.JFrame {

    /**
     * Creates new form playGame2
     */
    public playGame2() {  
        initComponents();
        setLocationRelativeTo(null);// coloca no centro do ecra
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arkanoidGame1 = new MyArkanoid.ArkanoidGame();
        fundonivel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(702, 565));
        setMinimumSize(new java.awt.Dimension(702, 565));
        setName("nivel2"); // NOI18N
        setPreferredSize(new java.awt.Dimension(715, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        arkanoidGame1.setBackground(new java.awt.Color(0, 0, 0));
        arkanoidGame1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        arkanoidGame1.setForeground(new java.awt.Color(255, 51, 51));
        arkanoidGame1.setMaximumSize(new java.awt.Dimension(600, 450));
        arkanoidGame1.setMinimumSize(new java.awt.Dimension(600, 450));
        arkanoidGame1.setLayout(new javax.swing.OverlayLayout(arkanoidGame1));
        getContentPane().add(arkanoidGame1);
        arkanoidGame1.setBounds(70, 50, 560, 470);

        fundonivel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nivel2.png"))); // NOI18N
        fundonivel2.setMaximumSize(new java.awt.Dimension(702, 563));
        fundonivel2.setMinimumSize(new java.awt.Dimension(702, 700));
        fundonivel2.setName(""); // NOI18N
        fundonivel2.setPreferredSize(new java.awt.Dimension(702, 563));
        getContentPane().add(fundonivel2);
        fundonivel2.setBounds(0, 0, 700, 563);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playGame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playGame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playGame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playGame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playGame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MyArkanoid.ArkanoidGame arkanoidGame1;
    private javax.swing.JLabel fundonivel2;
    // End of variables declaration//GEN-END:variables
}
