package arkanoide_exe;

import MyArkanoid.Créditos;
import MyArkanoid.Niveis;
import MyArkanoid.playGame;
import java.awt.Image;

/**
 *
 * @author Pedro Coelho - 25026
 * @author Jose Martins - 24269
 * 
 */

public class Arkanoide extends javax.swing.JFrame {

    /**
     * Creates new form Arkanoide
     */
    public Arkanoide() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCreditos = new javax.swing.JButton();
        niveis = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jogar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(702, 609));
        setResizable(false);
        getContentPane().setLayout(null);

        btCreditos.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btCreditos.setText("Creditos");
        btCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(btCreditos);
        btCreditos.setBounds(40, 510, 100, 39);

        niveis.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        niveis.setText("Niveis");
        niveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niveisActionPerformed(evt);
            }
        });
        getContentPane().add(niveis);
        niveis.setBounds(290, 510, 100, 40);

        sair.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(560, 510, 100, 40);

        jogar.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jogar.setText("Jogar");
        jogar.setMaximumSize(new java.awt.Dimension(85, 27));
        jogar.setMinimumSize(new java.awt.Dimension(85, 27));
        jogar.setPreferredSize(new java.awt.Dimension(85, 27));
        jogar.setRequestFocusEnabled(false);
        jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarActionPerformed(evt);
            }
        });
        getContentPane().add(jogar);
        jogar.setBounds(290, 460, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/smashtheageslogo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 696, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreditosActionPerformed
        new Créditos(this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btCreditosActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    private void jogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarActionPerformed
        setVisible(false);
        new playGame(this).setVisible(true);
        
    }//GEN-LAST:event_jogarActionPerformed

    private void niveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niveisActionPerformed
    //dispose();
    setVisible(false);
    new Niveis().setVisible(true);
    }//GEN-LAST:event_niveisActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arkanoide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arkanoide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arkanoide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arkanoide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Arkanoide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreditos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jogar;
    private javax.swing.JButton niveis;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
